### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by marscher** [bhmm/bhmm#27]
The current version (0.5.2) on PyPI is not installable, if Cython is not available. The fix for this is already in the repo, but I'd like to release soon.

@franknoe, @jchodera
Is there any progress on other issues which are worth waiting for or should I just release ASAP?

**Comment by franknoe** [comment]
I am handling the various combinations of estimation parameters 
(reversible / connected / stationary). There's progress, but it's more 
complicated than I thought. Since this is a patch release, no need to wait.

Am 11/01/16 um 19:33 schrieb Martin K. Scherer:

> The current version (0.5.2) on PyPI is not installable, if Cython is 
> not available. The fix for this is already in the repo, but I'd like 
> to release soon.
> 
> @franknoe https://github.com/franknoe, @jchodera 
> https://github.com/jchodera
> Is there any progress on other issues which are worth waiting for or 
> should I just release ASAP?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/bhmm/bhmm/issues/27.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by jchodera** [comment]
Go ahead and tackle the patch release!

**Comment by marscher** [comment]
done

**Comment by franknoe** [comment]
thanks

Am 12/01/16 um 00:12 schrieb Martin K. Scherer:

> done
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/bhmm/bhmm/issues/27#issuecomment-170728230.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
